### ISSUE TITLE
Unable to access Skybridge

### ISSUE THREAD

**Issue by mergesort** [videah/SkyBridge#35]
I confirmed on multiple devices, I can't seem to authenticate my account right now.
![Authentication](https://github.com/videah/SkyBridge/assets/716513/f20e42b7-00e0-4ce4-96e6-7a388e8dc2bc)

**Comment by MysticalOS** [comment]
Was coming to report same. they seem to have broken auth, app passwords and actual password alike

**Comment by videah** [comment]
Since 21:45 UTC yesterday bluesky started rejecting all sessions coming from the public SkyBridge instance, I suspect it had either been severely rate limited or blocked. I don't think this was intentional and reached out via email to see what was up. I haven't heard a response but as of 6:00 UTC sessions are now working.

Will have to keep an eye out for this happening in the future.

![image](https://github.com/videah/SkyBridge/assets/4761786/bddc6ed9-8ed9-40f5-9617-cd7d5f535cc6)

<img width="575" alt="image" src="https://github.com/videah/SkyBridge/assets/4761786/1ea1020d-056d-435b-afd0-bc952021ba32">

**Comment by videah** [comment]
As of 51aa822 user sessions are now stored long term in the database and refreshed appropriately, should hopefully prevent this from happening again.
