### ISSUE TITLE
Incorrect data format for Mona

### ISSUE THREAD

**Issue by LauraLangdon** [videah/SkyBridge#4]
In Mona, The Bluesky timeline gets "Error: the data couldn't be read because it isn't in the current format".

![image](https://github.com/videah/SkyBridge/assets/48335772/cf0589bd-0f10-4d00-b469-f454c9d7e79c)

Notifications load correctly, though!

**Comment by JunyuKuang** [comment]
Hi, thank you for reporting the issue, and thank @videah for creating this project. Mona’s developer here. I’ve made some client-side adjustments to make future versions of Mona compatible with this project, and I’d like to introduce some adjustment proposals so the project can work better with other Mastodon apps:

1. Account objects should have non-nil values for statuses_count, following_count, and followers_count. Using 0 as a fallback value should be sufficient. [Mastodon Doc](https://docs.joinmastodon.org/entities/Account/#statuses_count)
2. Currently date strings are returned as something like this: “2023-05-20T07:10:16.288” which by default is incompatible with Apple’s date formatter [ISO8601DateFormatter](https://developer.apple.com/documentation/foundation/iso8601dateformatter). To address it, a “Z” character needs to be added at the end, for example: “2023-05-20T07:10:16.288Z”
3. Some endpoints (e.g. [status lookup API](https://docs.joinmastodon.org/methods/statuses/#get)) expect a single object, but the server currently returns an array of objects instead, which can cause JSON parsing failure.

**Comment by videah** [comment]
Thank you @JunyuKuang! I knew I was doing some things wrong in subtle ways but hadn't had the time to investigate yet so I really appreciate being pointed in the right direction. These issues should hopefully be fixed in 51b5bb0897dc733aad5087affc2ed5a153a9188d, f8d6a38bf5950882eb11a6732d94329c861918f4, and 25e8eea353452af01b1e5f99eb56d23edb3ed984.

I have had quite a few people coming to me asking for Mona support so I'm excited to get it closer to a more usable state, I'll be doing some more testing with it shortly

**Comment by JunyuKuang** [comment]
Great, thank you for the quick fix!

**Comment by videah** [comment]
Since Mona is more or less working now, I will close this issue, any more issue reports are welcome!
